# Generated by Django 3.2.6 on 2021-08-08 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=42)),
                ('npwp', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=33)),
                ('city', models.CharField(max_length=33)),
                ('region', models.CharField(max_length=19)),
                ('post_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=36)),
                ('transaction_type', models.CharField(max_length=8)),
                ('commercial_invoice_number', models.CharField(max_length=13)),
                ('status_start', models.CharField(max_length=14)),
                ('status_tax_summary', models.CharField(max_length=11, null=True)),
                ('invoice_date', models.DateField(blank=True, default='', null=True)),
                ('due_date', models.DateField(blank=True, default='', null=True)),
                ('item_name', models.CharField(max_length=61)),
                ('unitprice', models.FloatField(blank=True, default='', null=True)),
                ('quantity', models.FloatField(blank=True, default='', null=True)),
                ('discount', models.FloatField(blank=True, default='', null=True)),
                ('gross_amount', models.FloatField(blank=True, default='', null=True)),
                ('tax_amount', models.FloatField(blank=True, default='', null=True)),
                ('total_amount', models.FloatField(blank=True, default='', null=True)),
                ('tax_period', models.CharField(blank=True, default='', max_length=7, null=True)),
                ('revision', models.IntegerField(blank=True, default='', null=True)),
                ('reported_date', models.DateTimeField(blank=True, default='', null=True)),
                ('reported_status', models.CharField(blank=True, default='', max_length=4, null=True)),
                ('reported_status_desc', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('tax_type', models.CharField(blank=True, default='', max_length=8, null=True)),
                ('tax_document_number', models.CharField(default='', max_length=14)),
                ('tax_document_date', models.DateField(blank=True, default='', null=True)),
                ('approved_date', models.DateTimeField(blank=True, default='', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendor')),
            ],
        ),
    ]
